### ISSUE TITLE
crash on start up after adding chisel 3 to my instance(mod conflict)

### ISSUE THREAD

**Issue by SDUBZ** [TheCricket/Chisel-3#1]
After adding chisel 3 it causes fancy fluid to crash 
crash report : http://pastebin.com/Rd6u3avG

chisel 3 version: Chisel3-3.0.jar
forge version : forge-1.9.4-12.17.0.1967.jar
[fml-client-latest (2).txt](https://github.com/Chisel-2/Chisel-3/files/322086/fml-client-latest.2.txt)

pack loads up normally after disabling chisel 3

new crash with instance with only those 2 mods 
crash 
[crash-2016-06-19_12.46.06-client.txt](https://github.com/Chisel-2/Chisel-3/files/322087/crash-2016-06-19_12.46.06-client.txt)

**Comment by TheCricket** [comment]
Fancy Fluid storage is not compatible with this chisel. It is their fault

**Comment by TheCricket** [comment]
Thank you for making a pretty good report though
