### ISSUE TITLE
Crash as well as deleting items

### ISSUE THREAD

**Issue by Jayceena** [TheCricket/Chisel-3#3]
I just saw that chisel had updated to 1.9.4 and had to have it so I installed it into my pack, went to do a few things, and crashed. Shift clicking out of the chisel did that, I could pick it out fine but shift clicking is a nope. Also I found if you leave something in the chisel and close and reopen it, it deletes the items.

**Comment by TheCricket** [comment]
Thanks will look into this today

**Comment by Jayceena** [comment]
Also you can't shift click into the chisel which I believe you were able to in Chisel 2.

**Comment by TheCricket** [comment]
This issue was moved to TheCricket/Chisel3#2
