### ISSUE TITLE
Blocks reverting to normal upon breaking

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [TheCricket/Chisel-3#4]
When I break chisel'd blocks they revert back to the original block and then when I try to chisel them back, there is a 0 in the corner of the block image that I had previously chisel'd. When I click on the block image the image disappears and I cannot re-chisel any blocks to that specific texture.

**Comment by TheCricket** [comment]
Could have sworn I fixed that. Will look at it later today. Thanks for the report

**Comment by awkwaRdcaRRot** [comment]
No problem!

**Comment by TheCricket** [comment]
This issue was moved to TheCricket/Chisel3#3
